services:
  web:
    build: .
    restart: unless-stopped
    develop:
      watch:
        - path: ./requirements.txt
          action: rebuild
        - path: ./src
          target: /app/src
          action: sync
        - path: ./migrations
          target: /app/migrations
          action: sync
        - path: ./alembic.ini
          target: /app/alembic.ini
          action: sync
    ports:
      - "8501:8501"
    volumes:
      - sqlite_data:/app/data
    environment:
      - DATABASE_URL=sqlite:////app/data/agency_accounting.db

volumes:
  sqlite_data: